apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: servianapp
  name: servian-deployment
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: servianapp
status:
  loadBalancer: {}